<?= $this->doctype() ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Cachuelapp')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/uikit.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/users_custom.js'))
            ->prependFile($this->basePath('js/canvas.js'))
            ->prependFile($this->basePath('js/uikit-icons.min.js'))
            ->prependFile($this->basePath('js/uikit.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
            <nav class="uk-navbar-container uk-margin uk-navbar" uk-navbar>        		
            	<div class="uk-navbar-left">
            		<a class="uk-navbar-item uk-logo" href="<?= $this->url('home') ?>">
                        <img class="uk-margin-top uk-margin-bottom uk-margin-left" src="<?= $this->basePath('img/logo_original.png') ?>" width="80" alt="Cachuelapp <?= \Admin\Module::VERSION ?>"/>
                        <span class="uk-visible@m uk-visible@l">&nbsp;&nbsp;CACHUELAPP</span>
                    </a>
                    <div class="uk-visible@m uk-visible@l">
                    	<?php 
                    	   echo $this->navigation('navigation')
                                  ->menu()
                                  ->setMinDepth(0)
                                  ->setMaxDepth(0)
                                  ->setUlClass('uk-navbar-nav');
                        ?>
                    </div>                    
                </div>                
        		<div class="uk-navbar-right">
        			
        			<div class="uk-navbar-item">
            			<?php if($this->identity()){ echo "<div>Bienvenido: <strong>" . $this->identity()['usuario'] . "</strong></div>";}?>		
            		</div> 
            		
        			<a class="uk-navbar-toggle uk-hidden@m uk-hidden@l" href="#">
                       <span class="uk-margin-small-right">Menu</span> <span uk-navbar-toggle-icon></span> 
                    </a>
        		</div>            
            </nav>
            
            <div class="uk-container" uk-height-viewport="offset-bottom: 32">
                <?= $this->content ?>
            </div>    
            <hr>
            <footer class="uk-margin-left">
                <p>&copy; <?= date('Y') ?> por Yapanax. Todos los derechos reservados. | <?= \Admin\Module::VERSION ?></p>
            </footer>
            
        <?= $this->inlineScript() ?>
    </body>    
</html>
