<?php // module/Empleos/view/empleos/index/index.phtml: ?>

<?php
$title = 'Empleos';
$this->headTitle($title);
?>

<h1 class="uk-text-center"><?= $this->escapeHtml($title) ?></h1>

<hr/>

	<?php
        if ($this->messages):
            foreach ($this->messages as $msg):
                ?>
                <div class="uk-label-success uk-padding-small uk-margin"><?php echo $msg; ?></div>
            <?php
            endforeach;
        endif;
   	?>
   	<?php
    if ($this->errorMessages):
        foreach ($this->errorMessages as $msg):
            ?>
				<div class="uk-label-danger uk-padding-small uk-margin">                         
					<?php echo $msg; ?>
				</div>
			<?php
			endforeach;
		endif;
	?>

<?php if ($this->empleos):?>

    <div class="uk-child-width-1-2 uk-grid-match" uk-grid >
        <?php foreach ($this->empleos as $empleo) : ?>
        <div class="uk-width-1-2@m uk-text-center uk-margin">
        	<div class="uk-card uk-card-default uk-card-body uk-card-hover">
                <h3 class="uk-text-center"><?= $this->escapeHtml($empleo->titulo) ?></h3>
                <hr class="uk-divider-small uk-text-center">
                <div class="uk-margin uk-width-medium uk-margin-auto uk-text-center">
                	<?= $this->escapeHtml($empleo->descripcion) ?>
                </div>
                <hr class="uk-divider-small uk-text-center">
                <div class="uk-margin uk-width-medium uk-margin-auto uk-text-center">                	
                    <?php
                    $date = new DateTime($this->escapeHtml($empleo->fechaCreacion));                     
                    ?>
                	<span uk-icon="icon: calendar"></span> <?= $date->format('d-m-Y'); ?> | 
                	<span uk-icon="">S/ </span><?= $this->escapeHtml($empleo->remuneracion) ?> | 
                	<span uk-icon="clock"></span><?= $this->escapeHtml($empleo->horas) ?>
                </div>
                <div class="location uk-margin uk-width-medium uk-margin-auto uk-text-center">
                	<span uk-icon="icon: location"></span> <?= $this->escapeHtml($empleo->Ubicacion->distrito) ?> - <?= $this->escapeHtml($empleo->Ubicacion->provincia) ?>
                </div>
                <div>
                    <a class="uk-button uk-button-primary" href="<?= $this->url('empleos', ['action' => 'postular-empleo', 'codEmpleo' => $empleo->codEmpleo]) ?>">Ver empleo</a>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
    
     <?php

     echo $this->paginationControl(

         $this->empleos,

         'sliding',

         'partial/paginator.phtml',

         array(
             'route' => 'empleos', 'action' => 'listar-empleos'
         )
     );
     ?>
    
<?php else:?>
	<p>¡No se han encontrado resultados!</p>
<?php endif;?>

<hr/>

<p>
	¿No encuentras lo que buscas? -<br/>
    <a href="<?= $this->url('empleos', ['action' => 'crear-empleo']) ?>">Crea tu propio empleo</a>
</p>