<?php // module/Empleos/view/empleos/index/listar-trabajadores.phtml: ?>

<?php
$title = 'Trabajadores';
$this->headTitle($title);
?>

<h1 class="uk-text-center"><?= $this->escapeHtml($title) ?></h1>

<?php if ($this->trabajadores):?>

    <table class="uk-table">
        <tr>
            <th>Nombres</th>
            <th>Primer Apellido</th>
            <th>Segundo Apellido</th>
            <th>Departamento</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($this->trabajadores as $trabajador) : ?>
        <tr>
            <td><?= $this->escapeHtml($trabajador->nombres) ?></td>
            <td><?= $this->escapeHtml($trabajador->primerApellido) ?></td>
            <td><?= $this->escapeHtml($trabajador->segundoApellido) ?></td>
            <td><?= $this->escapeHtml($trabajador->departamento) ?></td>
            <td>
                <a href="<?= $this->url('trabajadores', ['action' => 'ver-trabajador', 'codTrabajador' => $trabajador->codUsuario]) ?>">Ver Ficha</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    
<?php else:?>
	<p>¡No se han encontrado resultados!</p>
<?php endif;?>

<hr/>

<p>
	¿Aún no estás registrado?, <br/>
    <a href="<?= $this->url('registro') ?>">Registrate para acceder a los empleos</a>
</p>