<?php // module/Empleos/view/empleos/index/listar-trabajadores.phtml: ?>

<?php
$title = 'Trabajadores';
$this->headTitle($title);
?>

<h1 class="uk-text-center"><?= $this->escapeHtml($title) ?></h1>

<?php if ($this->trabajadores):?>

    <div class="uk-child-width-1-3 uk-grid-match" uk-grid >
        <?php foreach ($this->trabajadores as $trabajador) : ?>
        <div class="uk-width-1-3@m uk-text-center">
        	<div class="uk-card uk-card-default uk-card-body uk-card-hover">
                <h3><?php echo ucfirst(strtoupper($trabajador->nombres)) . ' ' . strtoupper($trabajador->primerApellido) . ' ' . strtoupper($trabajador->segundoApellido);?></h3>
                <hr class="uk-divider-small uk-text-center">
                <div class="uk-cover-container uk-height-small">
                	<canvas width="" height="180"></canvas>
                    <img src="<?php echo $this->basepath('img/perfil/');?><?= $this->escapeHtml($trabajador->imagenPerfil) ?>" alt="" uk-cover>
                </div>
                <div class="uk-margin uk-width-medium uk-margin-auto uk-text-center">
                	<?= $this->escapeHtml($trabajador->correo) ?>
                </div> 
                <div>               
                    <a class="uk-button uk-button-primary" href="<?= $this->url('perfil', ['action' => 'ver-perfil', 'codUsuario' => $trabajador->codUsuario]) ?>">Ver perfil</a>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
    
     <?php

     echo $this->paginationControl(

         $this->trabajadores,

         'sliding',

         'partial/paginator.phtml',

         array(
             'route' => 'trabajadores', 'action' => 'listar-trabajadores'
         )
     );
     ?>
    
<?php else:?>
	<p>¡No se han encontrado resultados!</p>
<?php endif;?>

<hr/>

<p>
	¿Aún no estás registrado?, <br/>
    <a href="<?= $this->url('registro') ?>">Registrate para acceder a los empleos</a>
</p>