<?= $this->doctype() ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Cachuelapp')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon2.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/uikit.min.css'))
            ->prependStylesheet($this->basePath('css/uikit-rtl.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/canvas.js'))
            ->prependFile($this->basePath('js/uikit-icons.min.js'))
            ->prependFile($this->basePath('js/uikit.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
            <nav class="uk-navbar-container uk-margin uk-navbar" uk-navbar>        		
            	<div class="uk-navbar-left">
            		<a class="navbar-brand " href="<?= $this->url('home') ?>">
                        <img class="uk-margin-top uk-margin-bottom uk-margin-left" src="<?= $this->basePath('img/logo.png') ?>" width="150" alt="Cacuelapp <?= \Application\Module::VERSION ?>"/>
                    </a>
                    <ul class="uk-navbar-nav">                    	
                        <li class="uk-active"><a href="<?= $this->url('home') ?>">Home</a></li>
                        <li class="uk-parent"><a href="">Empleos</a></li>
                    </ul>
                </div>
        		<div class="uk-navbar-right">
        			<a class="uk-navbar-toggle" uk-navbar-toggle-icon href=""></a>
        		</div>            
            </nav>
            
            <div class="uk-container">
                <?= $this->content ?>
            </div>    
            <hr>
            <footer class="uk-margin-left">
                <p>&copy; <?= date('Y') ?> por Yapanax. Todos los derechos reservados.</p>
            </footer>
            
        <?= $this->inlineScript() ?>
    </body>    
</html>
