
<?php 
$usuario = $this->usuario_helper($this->identity()['codUsuario'], $this->identity()['rol']);
//var_dump($usuario); //return ;
?>

<!-- DIV PRINCIPAL -->
<div class="" >
<div class="col-md-12" >	
	<div class="box">
		<div class="box-title">
			<h3>Editar perfil de usuario</h3>
			<span uk-icon="icon: reply"></span><a class="" href="<?php echo $this->url('perfil');?>">Volver</a>
		</div>
		<div class="box-body padding-md"> <!-- DIV BODY END -->
					
			<div class="uk-margin">
				<div class="col-md-12">
					<?php
						if ($this->messages):
							foreach ($this->messages as $msg):
								?>
								<div class="uk-text-success">                                        
									<?php echo $msg; ?>
								</div>
							<?php
							endforeach;
						endif;
					?>
					
					<?php
						if ($this->errorMessages):
							foreach ($this->errorMessages as $msg):
								?>
								<div class="uk-text-danger">                         
									<?php echo $msg; ?>
								</div>
							<?php
							endforeach;
						endif;
					?>	
				</div>
			</div>
			
			<div class="row" uk-grid>
				<div class="uk-width-1-2@l"><!-- EDITAR USUARIO -->
					<?php 
						$editarUsuarioForm = $this->editarUsuarioForm;
						$editarUsuarioForm->setAttribute('action', $this->url('perfil', array('action' => 'editar-perfil')));
						$editarUsuarioForm->setAttribute('class', 'form-horizontal');
						$editarUsuarioForm->prepare();
					?>
					<?php echo $this->form()->openTag($editarUsuarioForm);?>

						<?php echo $this->formHidden($editarUsuarioForm->get('csrf')); ?>

						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('nombres')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('nombres')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('nombres'));?>
							</div>
						</div>

						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('primerApellido')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('primerApellido')); ?>	
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('primerApellido'));?>
							</div>
						</div>

						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('segundoApellido')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('segundoApellido')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('segundoApellido'));?>
							</div>
						</div>
						
						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('numeroDNI')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('numeroDNI')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('numeroDNI'));?>
							</div>
						</div>
						
						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('enlaceFacebook')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('enlaceFacebook')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('enlaceFacebook'));?>
							</div>
						</div>
						
						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('fechaNacimiento')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('fechaNacimiento')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('fechaNacimiento'));?>
							</div>
						</div>

						<div class="form-group ">
							<?php echo $this->formLabel($editarUsuarioForm->get('correo')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('correo')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('correo'));?>
							</div>
						</div>

						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('celular')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('celular')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('celular'));?>
							</div>
						</div>
						
						<div class="uk-margin">
            				<?php echo $this->formLabel($editarUsuarioForm->get('Ubicacion')->get('direccion')) ?>
            				<div class="col-sm-10">
            					<?php echo $this->formInput($editarUsuarioForm->get('Ubicacion')->get('direccion')); ?>
            					<?php echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<div class="uk-text-danger">')
                                    ->setMessageSeparatorString('</div><div class="uk-text-danger">')
                                    ->setMessageCloseString('</div>')
                                    ->render($editarUsuarioForm->get('Ubicacion')->get('direccion'));?>
            				</div>
            			</div>
            			
            			<div class="uk-margin">
            				<?php echo $this->formLabel($editarUsuarioForm->get('Ubicacion')->get('distrito')) ?>
            				<div class="col-sm-10">
            					<?php echo $this->formInput($editarUsuarioForm->get('Ubicacion')->get('distrito')); ?>
            					<?php echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<div class="uk-text-danger">')
                                    ->setMessageSeparatorString('</div><div class="uk-text-danger">')
                                    ->setMessageCloseString('</div>')
                                    ->render($editarUsuarioForm->get('Ubicacion')->get('distrito'));?>
            				</div>
            			</div> 
            			
            			<div class="uk-margin">
            				<?php echo $this->formLabel($editarUsuarioForm->get('Ubicacion')->get('provincia')) ?>
            				<div class="col-sm-10">
            					<?php echo $this->formInput($editarUsuarioForm->get('Ubicacion')->get('provincia')); ?>
            					<?php echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<div class="uk-text-danger">')
                                    ->setMessageSeparatorString('</div><div class="uk-text-danger">')
                                    ->setMessageCloseString('</div>')
                                    ->render($editarUsuarioForm->get('Ubicacion')->get('provincia'));?>
            				</div>
            			</div>
            			
            			<div class="uk-margin">
            				<?php echo $this->formLabel($editarUsuarioForm->get('Ubicacion')->get('departamento')) ?>
            				<div class="col-sm-10">
            					<?php echo $this->formInput($editarUsuarioForm->get('Ubicacion')->get('departamento')); ?>
            					<?php echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<div class="uk-text-danger">')
                                    ->setMessageSeparatorString('</div><div class="uk-text-danger">')
                                    ->setMessageCloseString('</div>')
                                    ->render($editarUsuarioForm->get('Ubicacion')->get('departamento'));?>
            				</div>
            			</div> 
						
						<div class="uk-margin">
							<div class="col-sm-offset-2 col-sm-10">
								<?php echo $this->formElement($editarUsuarioForm->get('guardar')); ?>
							</div>
						</div>						

					<?php echo $this->form()->closeTag(); ?>				
				</div><!-- EDITAR USUARIO END -->
				
				<div class="uk-width-1-2@l"><!-- CAMBIO CLAVE -->
				<?php 
					$cambiarClaveForm = $this->cambiarClaveForm;
					$cambiarClaveForm->setAttribute('action', $this->url('perfil', array('action' => 'cambiar-clave')));
					$cambiarClaveForm->setAttribute('class', 'form-horizontal');
					$cambiarClaveForm->prepare();
				?>
				<?php echo $this->form()->openTag($cambiarClaveForm);?>

					<?php echo $this->formHidden($cambiarClaveForm->get('csrf')); ?>

					<div class="">
						<?php echo $this->formLabel($cambiarClaveForm->get('anteriorClave')) ?>
						<div class="col-sm-9">
							<?php echo $this->formInput($cambiarClaveForm->get('anteriorClave')); ?>
							<?php echo $this->formElementErrors()
							->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
							->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable ">')
							->setMessageCloseString('</div>')
							->render($cambiarClaveForm->get('anteriorClave'));?>
						</div>
					</div>

					<div class="uk-margin">
						<?php echo $this->formLabel($cambiarClaveForm->get('nuevaClave')) ?>
						<div class="col-sm-9">
							<?php echo $this->formInput($cambiarClaveForm->get('nuevaClave')); ?>	
							<?php echo $this->formElementErrors()
							->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
							->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
							->setMessageCloseString('</div>')
							->render($cambiarClaveForm->get('nuevaClave'));?>
						</div>
					</div>

					<div class="uk-margin">
						<?php echo $this->formLabel($cambiarClaveForm->get('confirmarNuevaClave')) ?>
						<div class="col-sm-9">
							<?php echo $this->formInput($cambiarClaveForm->get('confirmarNuevaClave')); ?>
							<?php echo $this->formElementErrors()
							->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
							->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
							->setMessageCloseString('</div>')
							->render($cambiarClaveForm->get('confirmarNuevaClave'));?>
						</div>
					</div>
					
					<div class="uk-margin">
						<div class="col-sm-offset-3 col-sm-9">
							<?php echo $this->formElement($cambiarClaveForm->get('enviar')); ?>
						</div>
					</div>										

				<?php echo $this->form()->closeTag(); ?>	
			</div><!-- CAMBIO CLAVE END -->
				
			</div>

		</div><!-- DIV BODY END -->
	</div>
</div>
</div>
<!-- DIV PRINCIPAL -->
