
<?php 
$usuario = $this->usuario_helper($this->identity()['codUsuario'], $this->identity()['rol']);
?>

<!-- DIV PRINCIPAL -->
<div class="row">
<div class="col-md-12">	
	<div class="box">
		<div class="box-title">
			<h3>Perfil de usuario</h3>
		</div>
		<div class="box-body padding-md"> <!-- DIV BODY END -->
			<div class="row"> <!-- IMAGEN + PERFIL -->
				<div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
					<?php 
						$subirImagenForm = $this->subirImagenForm;
						$subirImagenForm->setAttribute('action', $this->url('perfil', array('action' => 'subir-imagen')));
						$subirImagenForm->prepare();
					?>
					<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
					<?php echo $this->form()->openTag($subirImagenForm);?>
						<div id="profile">
							<a href="javascript:void(0);">
								<img src="<?php echo $this->basepath('public/img/perfil/');?><?php echo ($usuario['imagen'] == 'default') ? $usuario['imagen'] . '.png' :  $usuario['imagen']; ?>" class="profile-image img-rounded img-responsive" id="profileImg" width="200" height="auto"/>
								<span id="uploadTrigger"><b><i class="glyphicon glyphicon-camera" style="padding: 3px 9px; color: #E2DEE4;"></i>Modificar imagen</b></span>
								<?php echo $this->formFile($subirImagenForm->get('imagen')); ?>
							</a>
						</div>
						<div style="top: 2px;"></div>
						<div id="mensaje">Aquí aparecerá el error o percanse con la imagen</div>
					<?php echo $this->form()->closeTag(); ?>
				</div>

				<div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">
					<h3><?php echo ucfirst(strtolower($usuario['nombres'])) . ' ' . ucfirst(strtolower($usuario['primerApellido'])) . ' ' . ucfirst(strtolower($usuario['segundoApellido']));?></h3>
					<h4><?php echo strtoupper($usuario['rol']);?></h4>
					<h4><?php echo $usuario['correo'];?></h4>		
				</div>
			</div><!-- IMAGEN + PERFIL END -->
			
			<div class="row">
				<div class="col-md-6 padding-lg"><!-- EDITAR USUARIO -->
					<?php 
						$editarUsuarioForm = $this->editarUsuarioForm;
						$editarUsuarioForm->setAttribute('action', $this->url('perfil', array('action' => 'editar-perfil')));
						$editarUsuarioForm->setAttribute('class', 'form-horizontal');
						$editarUsuarioForm->prepare();
					?>
					<?php echo $this->form()->openTag($editarUsuarioForm);?>

						<?php echo $this->formHidden($editarUsuarioForm->get('csrf')); ?>

						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('Persona')->get('nombres')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('Persona')->get('nombres')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('Persona')->get('nombres'));?>
							</div>
						</div>

						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('Persona')->get('primerApellido')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('Persona')->get('primerApellido')); ?>	
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('Persona')->get('primerApellido'));?>
							</div>
						</div>

						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('Persona')->get('segundoApellido')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('Persona')->get('segundoApellido')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('Persona')->get('segundoApellido'));?>
							</div>
						</div>

						<div class="form-group ">
							<?php echo $this->formLabel($editarUsuarioForm->get('Persona')->get('correo')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('Persona')->get('correo')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('Persona')->get('correo'));?>
							</div>
						</div>

						<div class="form-group">
							<?php echo $this->formLabel($editarUsuarioForm->get('Persona')->get('celular')) ?>
							<div class="col-sm-10">
								<?php echo $this->formInput($editarUsuarioForm->get('Persona')->get('celular')); ?>
								<?php echo $this->formElementErrors()
													->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
													->setMessageCloseString('</div>')
													->render($editarUsuarioForm->get('Persona')->get('celular'));?>
							</div>
						</div>  
						
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<?php echo $this->formElement($editarUsuarioForm->get('guardar')); ?>
							</div>
						</div>						

					<?php echo $this->form()->closeTag(); ?>				
				</div><!-- EDITAR USUARIO END -->
				
				<div class="col-md-6 padding-lg"><!-- CAMBIO CLAVE -->
					<?php 
						$cambiarClaveForm = $this->cambiarClaveForm;
						$cambiarClaveForm->setAttribute('action', $this->url('perfil', array('action' => 'cambiar-clave')));
						$cambiarClaveForm->setAttribute('class', 'form-horizontal');
						$cambiarClaveForm->prepare();
					?>
					<?php echo $this->form()->openTag($cambiarClaveForm);?>

						<?php echo $this->formHidden($cambiarClaveForm->get('csrf')); ?>

						<div class="form-group">
							<?php echo $this->formLabel($cambiarClaveForm->get('anteriorClave')) ?>
							<div class="col-sm-9">
								<?php echo $this->formInput($cambiarClaveForm->get('anteriorClave')); ?>
								<?php echo $this->formElementErrors()
								->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
								->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable ">')
								->setMessageCloseString('</div>')
								->render($cambiarClaveForm->get('anteriorClave'));?>
							</div>
						</div>

						<div class="form-group">
							<?php echo $this->formLabel($cambiarClaveForm->get('nuevaClave')) ?>
							<div class="col-sm-9">
								<?php echo $this->formInput($cambiarClaveForm->get('nuevaClave')); ?>	
								<?php echo $this->formElementErrors()
								->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
								->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
								->setMessageCloseString('</div>')
								->render($cambiarClaveForm->get('nuevaClave'));?>
							</div>
						</div>

						<div class="form-group">
							<?php echo $this->formLabel($cambiarClaveForm->get('confirmarNuevaClave')) ?>
							<div class="col-sm-9">
								<?php echo $this->formInput($cambiarClaveForm->get('confirmarNuevaClave')); ?>
								<?php echo $this->formElementErrors()
								->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
								->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
								->setMessageCloseString('</div>')
								->render($cambiarClaveForm->get('confirmarNuevaClave'));?>
							</div>
						</div>

						<div class="form-group ">
							<?php echo $this->formLabel($cambiarClaveForm->get('captcha')) ?>
							<div class="col-sm-9">
								<?php echo $this->formCaptcha($cambiarClaveForm->get('captcha')); ?>
								<?php echo $this->formElementErrors()
								->setMessageOpenFormat('<div class="alert alert-error alert-dismissable bg-danger margin">')
								->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable bg-danger margin">')
								->setMessageCloseString('</div>')
								->render($cambiarClaveForm->get('captcha'));?>
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-sm-offset-3 col-sm-9">
								<?php echo $this->formElement($cambiarClaveForm->get('enviar')); ?>
							</div>
						</div>										

					<?php echo $this->form()->closeTag(); ?>	
				</div><!-- CAMBIO CLAVE END -->	
			</div>
			
			<div class="row">
				<div class="col-md-12">
					<?php
						if ($this->messages):
							foreach ($this->messages as $msg):
								?>
								<div class="padding-md bg-success">                                        
									<?php echo $msg; ?>
								</div>
							<?php
							endforeach;
						endif;
					?>
					
					<?php
						if ($this->errorMessages):
							foreach ($this->errorMessages as $msg):
								?>
								<div class="padding-md bg-danger">                         
									<?php echo $msg; ?>
								</div>
							<?php
							endforeach;
						endif;
					?>	
				</div>
			</div>
				
		</div><!-- DIV BODY END -->
	</div>
</div>
</div>
<!-- DIV PRINCIPAL -->
