<?php
$title = '¿Qué estás buscando?';
$this->headTitle($title);
?>

<h1 class="uk-text-center"><?= $this->escapeHtml($title) ?></h1>

<div class="" uk-grid>

    <div class="uk-width-1-3@l">
        <div class="">
            <a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">    
                <img class="uk-border-circle" src="http://zirtrex.net/wp-content/uploads/2017/06/petlovers.jpg" class="uk-box-shadow-large" alt="">    
        	</a>
        </div>
        <div class="uk-text-center">
            <h2><a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">PetsLovers</a></h2>
            <p>Nulla porttitor accumsan tincidunt.</p>
        </div>
    </div>
    
    <div class="uk-width-1-3@l"> 
    	<div class="">
            <a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">
                <img class="uk-border-circle" src="http://zirtrex.net/wp-content/uploads/2017/06/creatividad.jpg" class="uk-box-shadow-large" alt="">    
        	</a>
        </div>
        <div class="uk-text-center">
            <h2><a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">Creativos</a></h2>
            <p>Sed porttitor lectus nibh. Lorem ipsum dolor sit amet.</p>
        </div>
    </div>
    
    <div class="uk-width-1-3@l">
        <div class="">
            <a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">
                <img class="uk-border-circle" src="http://zirtrex.net/wp-content/uploads/2017/06/mil_oficios.jpg" class="uk-box-shadow-large" alt="">    
        	</a>
        </div>
        <div class="uk-text-center">
            <h2><a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">MilOficios</a></h2>
            <p>Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.</p>
    	</div>
    </div>
    
</div>

    
    




