<?php
$title = '¿Qué estás buscando?';
$this->headTitle($title);
?>

<h1 class="uk-text-center"><?= $this->escapeHtml($title) ?></h1>

<div class="" uk-grid>

    <div class="uk-width-1-3@l">
        <div class="">
            <a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">    
                <img class="uk-border-circle" src="<?= $this->basePath('img/Petlovers.png') ?>" class="uk-box-shadow-large" alt="">    
        	</a>
        </div>
        <div class="uk-text-center">
            <h2><a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">PetsLovers</a></h2>
            <p>Encuentra interesados en servicios de cuidado, paseo o transporte de mascotas.</p>
        </div>
    </div>
    
    <div class="uk-width-1-3@l"> 
    	<div class="">
            <a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">
                <img class="uk-border-circle" src="<?= $this->basePath('img/Creativos.png') ?>" class="uk-box-shadow-large" alt="">    
        	</a>
        </div>
        <div class="uk-text-center">
            <h2><a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">Creativos</a></h2>
            <p>Completa encargos artísticos, trabajos con alta demanda de subjetividad y talento.</p>
        </div>
    </div>
    
    <div class="uk-width-1-3@l">
        <div class="">
            <a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">
                <img class="uk-border-circle" src="<?= $this->basePath('img/Miloficios.png') ?>" class="uk-box-shadow-large" alt="">    
        	</a>
        </div>
        <div class="uk-text-center">
            <h2><a href="<?= $this->url('home', ['action' => 'elegir-opcion']) ?>">MilOficios</a></h2>
            <p>Conéctate con personas hábiles en diversos oficios y amplia tu red de trabajo.</p>
    	</div>
    </div>
    
</div>

    
    




