<?php
$title = 'Preguntas Frecuentes';
$this->headTitle($title);
?>

<h1 class="uk-text-center"><?= $this->escapeHtml($title) ?></h1>

<div class="uk-card uk-card-default uk-card-body uk-margin">

    <h2 class="uk-text-center">¡Envianos tus dudas y te atenderemos!</h2>
    
    <h3>¿Que es Cachuelapp?</h3>
    <p>Es una plataforma web creada para conectar jóvenes que no están ni estudiando ni trabajando (NINIs) con trabajos eventuales (o con proyección en el tiempo) de manera ágil, sencilla y segura. </p>
    
    <h3>¿Por que trabajos eventuales?</h3>
    <p>Al enfocarse en trabajos eventuales que son tendencia en el mercado laboral, lo que se busca es facilitar la contratación y acelerar el proceso de recuperación de las poblaciones afectadas.</p>
    
    <h3>Propuesta laboral</h3>
    <p>A nivel laboral y fiscal nuestra propuesta de innovación rompe con las altas tasas de informalidad en el trabajo, porque integrará todos sus usuarios con el sistema tributario nacional (SUNAT),
    siendo esta un prototipo digital nunca antes visto, pero requerido por los ODS, el Plan Bicentenario y diversos compromisos internacionales.</p>
    
    <h3>¿Quienes sómos? </h3>
    <p>Cachuelapp es una de las iniciativas de la ONG Yapanax y la agencia digital Dominia. </p>
    <p>Nuestra misión es detectar jóvenes talentos y formarlos en valores, 
    gestión de negocios y desarrollo sostenible para ser agentes de cambio en la sociedad mediante la realización de proyectos tecnológicos de desarrollo productivo.</p>
         
    
</div>

    
    




